-include ../../config.mk

SUBDIRS = common libflappy flappy-alternatives flappy-checkvers flappy-create flappy-fetch flappy-install flappy-query flappy-rindex flappy-uhelper flappy-remove flappy-digest

include ../../mk/subdir.mk
