TOPDIR = ../../../..
-include $(TOPDIR)/config.mk

TESTSSUBDIR = flappy/libflappy/config
TEST = config_test
EXTRA_FILES = Kyuafile flappy.cf flappy_nomatch.cf 1.include.cf 2.include.cf

include $(TOPDIR)/mk/test.mk
