name: Tests
on:
  pull_request:
  push:
    branches:
      - 'master'
      - 'ci-**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ubuntu:
    strategy:
      fail-fast: false
      matrix:
        c_compiler: [gcc, clang]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ matrix.c_compiler }} make pkgconf \
            zlib1g-dev libssl-dev libarchive-dev kyua atf-sh libatf-dev
      - name: Build
        env:
          CC: ${{ matrix.c_compiler }}
        run: |
          ./configure --enable-tests
          make -j"$(nproc)"
      - name: Check
        run: make check
  fedora:
    runs-on: ubuntu-latest
    container: registry.fedoraproject.org/fedora-minimal:43
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          dnf -y install gcc make pkgconf-pkg-config git libarchive-devel \
            openssl-devel zlib-devel kyua libatf-c-devel libatf-sh-devel
      - name: Build
        run: |
          ./configure --enable-tests
          make -j"$(nproc)"
      - name: Check
        run: make check
